port = 8004
secret = "test"
httpsPort = 1443
certPath = "./ssl/vc.easyrts.com.crt"
keyPath = "./ssl/vc.easyrts.com.key"

[api]
url = "https://vc.easyrts.com/"
token = "tfnysji2oduiol5e"

[redis]
addr = "127.0.0.1:6379"
password = "123456"
db = 0

[db]
driver = "sqlite3"
dsn = "easyrtc.db"
timezone = ""