port = 8004
secret = "test"
recordingUrl= "test"
# httpsPort = 1443
# certPath = "./ssl/vc.easyrts.com.crt"
# keyPath = "./ssl/vc.easyrts.com.key"

[api]
url = "https://vc.easyrts.com/"
token = "tfnysji2oduiol5e"

[db]
driver = "sqlite3"
dsn = "easyrtc.db"
timezone = ""